name: Build and Deploy Docs

on:
  push:
    branches:
      - main
    tags:
      - "*"
      
  workflow_dispatch:
  
jobs:
  build:
    permissions:
      contents: write
      pages: write
      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.5
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Build documentation
      run: |
        git fetch --tags
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          VERSION=latest
        else
          VERSION=$(git describe --tags)
        fi
        poetry install
        poetry run make -C docs html
        mkdir -p docs_build
        mv docs/build/html "docs_build/$VERSION"


    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs_build
